repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
        exclude: '\.(ts|tsx|js|jsx)$'
    -   id: trailing-whitespace
        exclude: '\.(ts|tsx|js|jsx)$'

-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    -   id: seed-isort-config
        files: '\.py$'

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    -   id: isort
        files: '\.py$'

-   repo: https://github.com/hhatto/autopep8
    rev: v2.3.1
    hooks:
    -   id: autopep8
        args: [--in-place, --aggressive, --aggressive, --max-line-length=120]
        files: '\.py$'
